language: python
sudo: required
dist: xenial
python: '3.7'

env:
  - DJANGO=2.1.7

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver

before_script:
  - 'export PATH=$PATH:/usr/lib/chromium-browser/'

branches:
  only:
    - master
    - development

install:
  - pipenv install

script:
  - python manage.py test
  - behave

deploy:
  provider: heroku
  strategy: git
  app:
    development: myrecommendations
  # travis encrypt $(heroku auth:token) --add deploy.api_key
  api_key:
    secure: cmIBk4fmvQP+q3Z4NzoxsB5Hcse+jVL0c8T25XFBNjB3Ax++XslCCPU5Mopt2BbWC/4HIwM5KlbGwerbN9U65cSjz/t8cLIh84A05XtX2UT8ibIpomeLmbx2wiIbksGrEm06cPldX2bnud6Jg0tsm2MIQNaA8fQC1j8bIOxMmy0=
